#helm repo add grafana https://grafana.github.io/helm-charts
#helm repo update
#helm install -n loki loki grafana/loki --values loki.values.yaml --version 6.6.2
---
loki:
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  ingester:
    chunk_encoding: snappy
  tracing:
    enabled: true
  querier:
    # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
    max_concurrent: 3

gateway:
  ingress:
    enabled: true
    hosts:
      - host: loki.gamesmith.localhost
        paths:
          - path: /
            pathType: Prefix

deploymentMode: Distributed

ingester:
  replicas: 1
querier:
  replicas: 1
  #maxUnavailable: 2
queryFrontend:
  replicas: 1
  #maxUnavailable: 1
queryScheduler:
  replicas: 1
distributor:
  replicas: 1
  #maxUnavailable: 2
compactor:
  replicas: 1
indexGateway:
  replicas: 1
  #maxUnavailable: 1

bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0

# Enable minio for storage
minio:
  enabled: true

# disable canary 
lokiCanary:
  enabled: false
test:
  enabled: false

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

singleBinary:
  replicas: 0

chunksCache:
  enabled: false
resultsCache:
  enabled: false
  