apiVersion: v1
kind: Service
metadata:
  namespace: szippy
  labels:
    app: mongo
  name: mongo-nodeport-svc
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 32000
  selector:
    app: mongo
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: gamesmith
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
