apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-pv
  namespace: szippy
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /gamesmith/data/db
