apiVersion: v1
kind: Secret
metadata:
  namespace: szippy
  name: szippy-secrets
data:
  aws_access_key: ZXJCUnF4Znh0ek1BM2thSXkvYXdoQ3VTK1BmeTNhbUJ2WG1tR2JtQw==
  aws_access_key_id: QUtJQTZPNkVLTU9MWDNMQjNQVTY=
  auth0_client_secret: LUo5TW42NjVNUkZPSzdObkpMQlFFNmRCUklvbmJjZGJwOTR1NTZEenRGU2RSekJ2bnZnVXVkTjlYQnBMOEpwWA==
  auth0_domain: ZGV2LWI1a3RtaHlxcHA0MjhyNWQudXMuYXV0aDAuY29t
  auth0_clientid: UkNVTnNKakdKR2xHUzdiNnRHYW9DN29jTUJVeXpYUmo=
  openapi_key: c2stZTlFZFZrNWtKa3A0eUlmSFU0ODFUM0JsYmtGSlJJUEM0QTlKWGFJaHhQeEpkVkxl
  mongo_password: VGhpc0lzQ3Jpc3B5IQ==
  mongo_username: YWRtaW4=
  mongo_service_url: bW9uZ29kYjovL2FkbWluOlRoaXNJc0NyaXNweSFAbW9uZ28tbm9kZXBvcnQtc3ZjOjI3MDE3L3dlbHRlbmJhdWVu

# mongodb://admin:ThisIsCrispy!@mongo-nodeport-svc:27017/weltenbauen