apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nginx-test-registry 
  labels: 
    app: nginx-test-registry 
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: nginx-test-registry 
  template:  
    metadata: 
      labels: 
        app: nginx-test-registry 
    spec: 
      containers: 
      - name: nginx-test-registry 
        image: k3d-szippy-registry.localhost:12345/mynginx:v0.1
        ports: 
        - containerPort: 80
        volumeMounts:
        - name: workdir
          mountPath: /szippy
      volumes:
      - name: workdir
        hostPath:
          path: /szippy
